### ISSUE TITLE
Communication failures between containers due to name resolution

### ISSUE THREAD

**Issue by fcatae** [DXBrazil/ArdaContainers#1]
Containers don't see each other.

docker-compose
```
version: '2.1'
services:
  main:
     image: fcatae/ardafull
     command: run.cmd Arda.Main
     env_file: environment_secrets.env
     ports:
        - "80:80"
        - "443:443"
     depends_on:
        - kanban
        - permissions
        - reports
  kanban:
     image: fcatae/ardafull
     hostname: kanban
     command: run.cmd Arda.Kanban
     env_file: environment_secrets.env
     ports:
        - "81:81"
  permissions:
     image: fcatae/ardafull
     hostname: permissions
     command: run.cmd Arda.Permissions
     env_file: environment_secrets.env
     ports:
        - "82:82"
  reports:
     image: fcatae/ardafull
     hostname: reports
     command: run.cmd Arda.Reports
     env_file: environment_secrets.env
     ports:
        - "83:83"     
networks:
  default:
    external:
      name: nat
```
